---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# drone: **D**ata fo**R** ge**O**m e**N**cyclopa**E**dia

<!-- badges: start -->
<!-- badges: end -->

This package serves as a companion to the [Data Visualization Geometries Encyclopedia](https://thiyangt.github.io/geom.encyclopedia/) by [Thiyanga S. Talagala](https://thiyanga.netlify.app/)

## Installation

You can install the development version of drone from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("thiyangt/drone")
```

## Dataset


Load datasets related to the Encyclopedia

```{r example}
library(drone)
```


```{r}
library(tibble)
data("WorldHappinessScore")
WorldHappinessScore
```

```{r}
data("worldbankdata")
worldbankdata
```

```{r}
library(visdat)
vis_dat(worldbankdata)
vis_miss(worldbankdata)
```

```{r}
library(naniar)
gg_miss_upset(worldbankdata)
```

### Extract geoms

```{r}
library(ggplot2)
drone::extract_geoms(ggplot2, "^geom_s")
```
